In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])


In [ ]:
print(a)
print(f"dimension : {a.ndim} , shape : {a.shape}, size (total num of item) : {a.size} ")
print(f"datatype of item : {a.dtype}, item size : {a.itemsize}")
print(f"total size  (num of bytes): {a.size * a.itemsize}, total size (num of bytes): {a.nbytes}  ")

[1 2 3 4]
dimension : 1 , shape : (4,), size (total num of item) : 4 
datatype of item : int64, item size : 8
total size  (num of bytes): 32, total size (num of bytes): 32  


In [ ]:
a= np.array([[1,2,3,4]], dtype='int16')

In [ ]:
print(a)
print(f"dimension : {a.ndim} , shape : {a.shape}, size (total num of item) : {a.size} ")
print(f"datatype of item : {a.dtype}, item size : {a.itemsize}")
print(f"total size  (num of bytes): {a.size * a.itemsize}, total size (num of bytes): {a.nbytes}  ")

[[1 2 3 4]]
dimension : 2 , shape : (1, 4), size (total num of item) : 4 
datatype of item : int16, item size : 2
total size  (num of bytes): 8, total size (num of bytes): 8  


In [ ]:
b =  np.array([[1.0,2.9,3.7],[3.2,2.1,6.0]])

In [ ]:
print(b)
print(f"dimension : {b.ndim} , shape : {b.shape}, size (total num of item) : {b.size} ")
print(f"datatype of item : {b.dtype}, item size : {b.itemsize}")
print(f"total size  (num of bytes): {b.size * b.itemsize}, total size (num of bytes): {b.nbytes}  ")

[[1.  2.9 3.7]
 [3.2 2.1 6. ]]
dimension : 2 , shape : (2, 3), size (total num of item) : 6 
datatype of item : float64, item size : 8
total size  (num of bytes): 48, total size (num of bytes): 48  


In [ ]:
#Accessing and changing item

In [ ]:
a= np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [ ]:
print(a[0],a[0].shape)

[1 2 3 4 5 6] (6,)


In [ ]:
print(a[0,:],a[0,:].shape)

[1 2 3 4 5 6] (6,)


In [ ]:
a[1]

array([ 7,  8,  9, 10, 11, 12])

In [ ]:
a[1,4]

11

In [ ]:
a[1,-3]

10

In [ ]:
a[1,3]= 99

In [ ]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 99, 11, 12]])

In [ ]:
a[:,2]

array([3, 9])

In [ ]:
a[:,2] =22

In [ ]:
a

array([[ 1,  2, 22,  4,  5,  6],
       [ 7,  8, 22, 99, 11, 12]])

In [ ]:
a[:,1] =[100,101]

In [ ]:
a

array([[  1, 100,  22,   4,   5,   6],
       [  7, 101,  22,  99,  11,  12]])

In [ ]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b.shape

(2, 2, 2)

In [ ]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
b[0,1,:]

array([3, 4])

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[:,1,1]

array([4, 8])

In [ ]:
b[:,1,:]=[[20,21],[22,23]]

In [ ]:
b

array([[[ 1,  2],
        [20, 21]],

       [[ 5,  6],
        [22, 23]]])

In [ ]:
#Intialize different type of array

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4),dtype='int16')

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [ ]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.full((2,2),99,dtype='float16')

array([[99., 99.],
       [99., 99.]], dtype=float16)

In [ ]:
np.full(a.shape,99)

array([[99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99]])

In [ ]:
np.full_like(a,77)

array([[77, 77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77, 77]])

In [ ]:
np.random.rand(4,2)

array([[0.06226602, 0.40093324],
       [0.28265718, 0.60607465],
       [0.91639685, 0.57350195],
       [0.26587827, 0.41776411]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.07631249, 0.71240762, 0.2366637 , 0.69672837, 0.41454988,
        0.68516018],
       [0.04822931, 0.22547627, 0.77780915, 0.73852086, 0.55843506,
        0.8807818 ]])

In [ ]:
np.random.randint(99)

95

In [ ]:
np.random.randint(9, size=(2,3))

array([[1, 1, 6],
       [0, 0, 4]])

In [ ]:
np.random.randint(6,9, size=(2,3))

array([[8, 7, 8],
       [6, 6, 8]])

In [ ]:
np.random.randint(-6,9, size=(2,3))

array([[-2, -3,  3],
       [ 2, -6, -3]])

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
a=np.array([1,2,3])
r = np.repeat(a,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [ ]:
a=np.array([[1,2,3]])
r = np.repeat(a,3)
print(r)

[1 1 1 2 2 2 3 3 3]


In [ ]:
a=np.array([[1,2,3]])
r = np.repeat(a,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.array([[1,2,3]])
r = np.repeat(a,3,axis=1)
print(r)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
#practice

In [ ]:
out=np.ones((5,5),dtype='int16')
print(out)
zeros = np.zeros((3,3))
print(zeros)
out[1:-1,1:-1]=zeros
print(out)
out[2,2]=9
print(out)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#copy
a = np.array([[1,2,3],[4,5,6]])
b=a
b[0]=100
print("a",a)
print("b",b)

a [[100 100 100]
 [  4   5   6]]
b [[100 100 100]
 [  4   5   6]]


In [ ]:
#copy
a = np.array([[1,2,3],[4,5,6]])
b=a.copy()
b[0]=100
print("a",a)
print("b",b)

a [[1 2 3]
 [4 5 6]]
b [[100 100 100]
 [  4   5   6]]
