In [ ]:
import numpy as np

In [ ]:
a= np.array([1,2,3,4])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
b=np.array([1,1,2,2])

In [ ]:
a+b

array([2, 3, 5, 6])

In [ ]:
#Linear algebra

In [ ]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b=np.full((3,2),2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [ ]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.],
       [6., 6.]])

In [ ]:
id=np.identity(3)
id

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.linalg.det(id)

1.0

Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])

In [ ]:
np.min(stats)

1

In [ ]:
np.min(stats,axis = 0)

array([1, 2, 3])

In [ ]:
np.min(stats,axis = 1)

array([1, 4])

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats)

21

In [ ]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [ ]:
np.sum(stats,axis=1)

array([ 6, 15])

Rearrange

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
before.reshape((1,8))

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [ ]:
before.reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
before.reshape((4,2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
before.reshape((2,2,2))

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
#Vertical stack

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2,v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#Horizontal stack

In [ ]:
h1 = np.array([[1,2,5],[9,2,7]])
h2 = np.array([[3,4,5],[10,11,8]])
np.hstack((h1,h2))

array([[ 1,  2,  5,  3,  4,  5],
       [ 9,  2,  7, 10, 11,  8]])

Miscellaneous


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')

In [ ]:
filedata

array([[  1.,   2.,   3.,   4.,   5.,   6.,  77.,  33.,  53., 767.,  78.,
        763., 234.,  56.,  24.,   6.,  64.,   4.],
       [ 45.,   6.,  76.,   2.,   9.,  80.,  46.,   2.,  12.,  53.,  21.,
         71.,  65.,  15.,  63.,  52.,  84.,  90.],
       [ 99.,  34.,  21.,  65.,   7.,  76.,  41.,  26.,  73.,  26., 686.,
         88.,  32.,  18.,  98.,  54.,  65.,  12.]])

In [ ]:
filedata > 50

array([[False, False, False, False, False, False,  True, False,  True,
         True,  True,  True,  True,  True, False, False,  True, False],
       [False, False,  True, False, False,  True, False, False, False,
         True, False,  True,  True, False,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True, False, False,  True,
        False,  True,  True, False, False,  True,  True,  True, False]])

In [ ]:
filedata[filedata > 50]

array([ 77.,  53., 767.,  78., 763., 234.,  56.,  64.,  76.,  80.,  53.,
        71.,  65.,  63.,  52.,  84.,  90.,  99.,  65.,  76.,  73., 686.,
        88.,  98.,  54.,  65.])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[2,3,4,5,6]]

array([3, 4, 5, 6, 7])

In [ ]:
np.any(filedata > 50,axis =0)

array([ True, False,  True,  True, False,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [ ]:
np.any(filedata > 50,axis =1)

array([ True,  True,  True])

In [ ]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False, False,  True, False,  True,
        False,  True, False, False,  True, False, False,  True, False],
       [False, False,  True, False, False,  True, False, False, False,
         True, False,  True,  True, False,  True,  True,  True,  True],
       [ True, False, False,  True, False,  True, False, False,  True,
        False, False,  True, False, False,  True,  True,  True, False]])

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True,  True, False,  True, False,
         True, False,  True,  True, False,  True,  True, False,  True],
       [ True,  True, False,  True,  True, False,  True,  True,  True,
        False,  True, False, False,  True, False, False, False, False],
       [False,  True,  True, False,  True, False,  True,  True, False,
         True,  True, False,  True,  True, False, False, False,  True]])

In [ ]:
def subsequence(inp, out):
    print("___________________________________________")
    print("0",inp,out)
    if len(inp) == 0:
        print(out)
        return
    print("1",inp,out)
    subsequence(inp[1:], out + inp[0])
    print("2",inp,out)
    subsequence(inp[1:], out)

subsequence("xyz", "")

___________________________________________
0 xyz 
1 xyz 
___________________________________________
0 yz x
1 yz x
___________________________________________
0 z xy
1 z xy
___________________________________________
0  xyz
xyz
2 z xy
___________________________________________
0  xy
xy
2 yz x
___________________________________________
0 z x
1 z x
___________________________________________
0  xz
xz
2 z x
___________________________________________
0  x
x
2 xyz 
___________________________________________
0 yz 
1 yz 
___________________________________________
0 z y
1 z y
___________________________________________
0  yz
yz
2 z y
___________________________________________
0  y
y
2 yz 
___________________________________________
0 z 
1 z 
___________________________________________
0  z
z
2 z 
___________________________________________
0  



In [ ]:
def display(arr, index):
    if index < len(arr):
        print(arr[index], end=" ")
        display(arr, index+1)

arr = [1, [2, 3], [4, [5, 6]], 7]
display(arr, 0)